### ISSUE TITLE
Builds fails for apps using webpack 5

### ISSUE THREAD

**Issue by karangarg45** [stalniy/ucast#27]
Hi,

In our app we use webpack 5 and ucast throws some error while building the app. On investigating i found that the error happens because of the type field defined here 
https://github.com/stalniy/ucast/blob/master/packages/core/package.json#L5

Here the type is defined as commonjs so webpack looks at this field and decide that this is a commonjs package.
Here is a similar issue
https://github.com/webpack/webpack/issues/11597
https://github.com/projectfluent/fluent.js/issues/517

It  would be better if ucast remove the type field from all the packages' package.json. Then webpack can look at other field like module,main and decide which bundle to use.

**Comment by stalniy** [comment]
Thanks for the issue. Makes sense!  Can you provide a fix for this?

**Comment by karangarg45** [comment]
Sure i will try to raise a PR for this

**Comment by stalniy** [comment]
just released the patches for all versions, please try and let me know whether it fixes your issue

**Comment by karangarg45** [comment]
Thanks for the new versions. I will test them in my app and will let you know.
