### ISSUE TITLE
Implement Objection interpreter

### ISSUE THREAD

**Issue by stalniy** [stalniy/ucast#3]
- [x] this interpreter should be part of a new package `@ucast/objection` (put it in `packages/objection`)
- [ ] it should support the same operators as js interpreter from `@ucast/js` (except `$all`, `$where`, `$size`. `$elemMatch` operates only on related table and always perform a join)
- [x] it should allow to pass custom operators
- [x] it should use `createInterpreter` function from `@ucast/core` to create `interpret` function
- [x] the return value of `interpret` function is a Objection.js query builder
- [x] it should take initial query builder as an argument
- [x] auto join support on related table
- [ ] when it finds `condition.field` with dots inside it's a hint that this property is either of JSON type or a relation to another table. Using Objection.js API we should be able to understand and if a field construct query for JSON field and if it's a relation add `INNER JOIN` + where conditions (JSON support only)

**Comment by stalniy** [comment]
@otaviosoares This is the issue I'd like you to work on. You can find the list of requirements in the description

**Comment by otaviosoares** [comment]
Just bringing our conversation here. First of all, thank you for guiding me through it.

I believe I've implemented most of these topics now. I'm creating a WIP PR so you can point any issues with the implementation.

**Comment by stalniy** [comment]
Very nice @otaviosoares! I left few comments and suggestions but most of them are minor

**Comment by stalniy** [comment]
I removed JSON data type support for now. Let's wait the request from users and actual use cases. Because for example in Postgres this can be done in different ways.

Anyway, JSON support can be implemented with the help of custom operators, so it can be done as an extension.

Thank you @otaviosoares very much for your contribution! If you want to become a part of **ucast** project, let me know and will add you as a member of this repository

**Comment by otaviosoares** [comment]
Thank you for the support. Great work.
