### ISSUE TITLE
Question on how to go about using casl + mikro-orm together

### ISSUE THREAD

**Issue by JaneJeon** [stalniy/ucast#35]
Hi, I understand that there is a `@ucast/sql` package, but mikro-orm also supports MongoDB queries. And that made me think, could we possibly use `const { rulesToQuery } = require('@casl/ability/extra')` to construct `accessibleBy`?

If that's the case, would you recommend that people who want to use casl and mikro-orm together go down the `rulesToQuery` -> mongo operator -> mikro-orm route, or the `@ucast/sql` -> raw sql -> mikro-orm route?

Thanks

**Comment by stalniy** [comment]
I think the proper way is to use SQL adapter, don't know how good MikroORM at translating MongoDB query to SQL. Anyway, having SQL under the hood can allow to add more complicated operators.
