### ISSUE TITLE
Not accect array values for TypeOrm qb

### ISSUE THREAD

**Issue by MichaelSh2** [stalniy/ucast#41]
I got arr in (?, ?) instead of ('one', 'two')

![int_problem](https://user-images.githubusercontent.com/112966220/218508548-f65ec9f7-13eb-4f11-9b8f-8b42ea316711.png)

**Comment by stalniy** [comment]
This is expected, right? Otherwise you could produce sql injection ;)

**Comment by MichaelSh2** [comment]
In this case, I have a stupid questions). How to set real variables instead of `?` ?
I mean the first idea its just pelace first with $0, second $1...
But is it a good option?

**Comment by stalniy** [comment]
This is what type ORM should do for you. Doesn’t it do it ?

**Comment by MichaelSh2** [comment]
Actually no. Only way I force it to work, when replace all `?, ?, ?...` to `:0, :1, :2...`. But here is also a roblem with empty values.
E.g. { operator: 'in', value: [] } => 'in()' and postgres(in my case) throw error

**Comment by stalniy** [comment]
which version of @ucast/sql do you use? there is alpha version which properly format this. It contains the latest most stable/tested changes -> https://github.com/stalniy/ucast/blob/alpha/packages/sql/src/lib/typeorm.ts#L28-L31

But I haven't worked on this package for quite a lot of time. You probably know, we have a war in Ukraine and Open Source activity is currently is the least important thing I need to do

**Comment by MichaelSh2** [comment]
🫤 Yes, u right, I used 1.0.0-alpha.1 version.
Now it works right with variables, Thanks! 👍
But with empty vars, still the same (

Так, за ситуацію в країні знаю на своїй шкурі(

**Comment by stalniy** [comment]
there are actually 2 ways to handle empty vars:
* fail safe - log warning + fallback to smth like FALSE
* fail fast - throw an exception.

You are using AST nodes directly, but instead you should create your own Parser (or use MongoQueryParser from @ucast/mongo package). It has an ability to validate user input for errors.

For example, [MongoQueryParser](https://github.com/stalniy/ucast/blob/master/packages/mongo/src/instructions.ts#L93) fail fast but I also implemented a separate parser (for commercial project) where I used fail safe strategy.
